### ISSUE TITLE
Question: Data Driven Framework

### ISSUE THREAD

**Issue by jamesnyika** [ohpauleez/data-driven-slides#1]
Paul
 I loved this talk immensely and I wanted to ask if you have abstracted out into a library or example, the ideas you implemented for Consumer Reports ? 

 Is any of the code for what you did available  ? 

 thank
James

**Comment by ohpauleez** [comment]
It has been captured in a library called Vase, which is being cleanup up and reviewed now.  It will be released as open source soon - the announcement should appear on the Clojure mailing list.

**Comment by jamesnyika** [comment]
Thank you Paul!!!
